version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 6
  complex-logic:
    enabled: true
    config:
      threshold: 10
  file-lines:
    enabled: true
    config:
      threshold: 350
  method-complexity:
    enabled: true
    config:
      threshold: 10
  method-count:
    enabled: true
    config:
      threshold: 25
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
    checks:
      complexity:
        enabled: false
exclude_patterns:
  - ".github/"
  - ".husky/"
  - ".vscode/"
  - "**/node_modules/"
  - "site/"
  - "**/*.d.ts"
  - "**/*.test.js"
