---
root: true

parserOptions:
  ecmaVersion: 2019

env:
  node: true
  es6: true
  jest: true

plugins:
  - 'jsdoc'
  - 'node'
  
extends:
  - 'xo-space/esnext'
  - 'plugin:jsdoc/recommended'
  - 'plugin:node/recommended'

rules:
  array-element-newline: off
  capitalized-comments: off
  curly: ['error', 'multi-line']
  object-curly-spacing: ['error', 'always']
  no-multiple-empty-lines: ['error', { max: 2, maxEOF: 1, maxBOF: 0 }]
  no-negated-condition: off
  keyword-spacing: ['error', { overrides: { if: { after: false }, for: { after: false }, while: { after: false }, catch: { after: false } } }]
  jsdoc/newline-after-description: off
