---
root: true

ignorePatterns:
  - 'node_modules/**/*'
  - 'dist'
  - 'site'

env:
  node: true
  es6: true
  jest: true

plugins:
  - 'jsdoc'
  - '@typescript-eslint/eslint-plugin'

extends:
  - 'xo-space'
  - 'plugin:jsdoc/recommended'

rules:
  array-element-newline: off
  capitalized-comments: off
  curly: ['error', 'multi-line']
  comma-dangle: ['error', 'never']
  object-curly-spacing: ['error', 'always']
  operator-linebreak: ['error', 'after']
  no-multiple-empty-lines: ['error', { max: 2, maxEOF: 1, maxBOF: 0 }]
  no-negated-condition: off
  keyword-spacing: ['error', { overrides: { if: { after: false }, for: { after: false }, while: { after: false }, catch: { after: false } } }]
  jsdoc/newline-after-description: off

overrides:
  - files: ['*.ts']
    parserOptions:
      project:
        - './tsconfig.eslint.json'
        - './tsconfig.spec.json'
    extends:
      - 'xo-typescript/space'
    rules:
      '@typescript-eslint/keyword-spacing': ['error', { overrides: { if: { after: false }, for: { after: false }, while: { after: false }, catch: { after: false } } }]
      '@typescript-eslint/object-curly-spacing': ['error', 'always']
      '@typescript-eslint/comma-dangle': ['error', 'never']
      '@typescript-eslint/naming-convention': off
