---
root: true

env:
  browser: true
  node: true

parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  sourceType: module
  ecmaFeatures:
    jsx: true

globals:
  __PATH_PREFIX__: true
  babelOptions:
    plugins:
      - 'babel-plugin-styled-components'
    presets:
      - 'babel-preset-gatsby'

extends:
  - 'xo-space/esnext'
  - 'xo-react/space'

settings:
  react:
    version: detect

rules:
  array-element-newline: off
  capitalized-comments: off
  curly: ['error', 'multi-line']
  object-curly-spacing: ['error', 'always']
  no-multiple-empty-lines: ['error', { max: 2, maxEOF: 1, maxBOF: 0 }]
  no-negated-condition: off
  keyword-spacing: ['error', { overrides: { if: { after: false }, for: { after: false }, while: { after: false }, catch: { after: false } } }]
  react/jsx-tag-spacing: ['error', { closingSlash: 'never', beforeSelfClosing: 'always', afterOpening: 'never', beforeClosing: 'never' }]
  react/no-danger: off
  react/boolean-prop-naming: off
  react/no-array-index-key: off
  react/jsx-fragments: off
  react/no-unescaped-entities: ['error', { forbid: ['>', '}' ] }]
