blank_issues_enabled: false
contact_links:
  - name: Questions and Help
    url: https://github.com/KyleRoss/node-lambda-log/discussions
    about: Ask questions and get help here.
  - name: Contact Author
    url: https://kyleross.me/contact
    about: Contact the author directly for security alerts.
  - name: Gitter Chat
    url: https://gitter.im/KyleRoss/node-lambda-log
    about: Communicate with the community when you need support quickly.
