name: module
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        node: [ '12', '14', '16', '18' ]
    name: test/node v${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node v${{ matrix.node }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm i
      - name: Run Tests
        run: npm test

  coverage:
    name: Code Coverage
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - name: Run Tests
        if: ${{ github.event_name == 'pull_request' }}
        run: npm test
      - name: Run codacy-coverage-reporter
        if: ${{ github.event_name == 'pull_request' }}
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/lcov.info
      - name: Upload Coverage to Code Climate
        uses: paambaati/codeclimate-action@v2.7.2
        if: ${{ github.event_name == 'push' }}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm test
          coverageLocations: |
            ${{ github.workspace }}/coverage/lcov.info:lcov

  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - name: Delete expired artifacts
        uses: LKP-RnD/purge-expired-artifacts-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_to_purge: "KyleRoss/node-lambda-log"
          dry_run: "false"
      - uses: bradennapier/eslint-plus-action@v3.4.2
        with:
          includeGlob: 'index.js,index.test.js,lib/*.js'

  release:
    name: Release
    if: ${{ github.event_name == 'push' }}
    needs: [ test, coverage ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
